default: &default
  adapter: postgresql
  encoding: unicode
  username:
  password:
  port: 5433
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: exchanger_development

test:
  <<: *default
  database: exchanger_test

production:
  <<: *default
  database: exchanger_production
  username: exchanger
  password: <%= ENV['EXCHANGER_DATABASE_PASSWORD'] %>
